- hosts: k8s_node
  gather_facts: false
  any_errors_fatal: true
  vars:
    vars_path_arg: "--vars-path {{ ki_tmp_vars_path }}"
  tasks:
    - name: Execute setup-aipub-environment.sh
      shell: "sudo {{ ki_env_scripts_path }}/k8s-node/charts/aipub/setup-aipub-environment.sh {{ vars_path_arg }}"
      when: inventory_hostname == k8s_cp_nodes | first
